### ISSUE TITLE
Protontricks crashes when any game is selected

### ISSUE THREAD

**Issue by ohno1052** [Matoking/protontricks#309] opened 2024-07-02 09:56 UTC
**Describe the bug**
When I try to launch protontricks for any game it crashes, log below

**To Reproduce**
Run protontricks gui, select any game, crash

**Expected behavior**
Protontricks working normally (need to install some dlls for cyberpunk mods)

**System (please complete the following information):**
 - Distro: SteamOS 3.6
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.11.1
 - Steam version: Steam Deck Beta (for new steam families)

**Additional context**
Steam Deck LCD 64gb, all games and their compatdata are on the sdcard
Here's the log:

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.6.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 2348590
Multiple compatdata directories found for app 1210320
Multiple compatdata directories found for app 881100
Multiple compatdata directories found for app 1715130
Multiple compatdata directories found for app 1687950
Multiple compatdata directories found for app 1382330
Multiple compatdata directories found for app 729040
Multiple compatdata directories found for app 275850
Multiple compatdata directories found for app 287700
Multiple compatdata directories found for app 1151640
Multiple compatdata directories found for app 208650
Multiple compatdata directories found for app 2161700
Multiple compatdata directories found for app 1493710
Multiple compatdata directories found for app 2805730
Multiple compatdata directories found for app 597170
Multiple compatdata directories found for app 368340
Multiple compatdata directories found for app 289070
Multiple compatdata directories found for app 977950
Multiple compatdata directories found for app 1113000
Multiple compatdata directories found for app 322170
Multiple compatdata directories found for app 225540
Multiple compatdata directories found for app 548430
Multiple compatdata directories found for app 1794680
Multiple compatdata directories found for app 1091500
Currently logged-in Steam user: verycoolsteamusername
Shortcut Konsole (2957296905) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider

**Comment by Matoking** [comment] 2024-07-02 10:25
Duplicate of #304

**Closed by Matoking** 2024-07-02 10:25 UTC
