### ISSUE TITLE
Prefix menu not opening

### ISSUE THREAD

**Issue by Romz24** [Matoking/protontricks#188] opened 2022-12-03 21:27 UTC
**Describe the bug**
When I change the system language which is different from English, the prefix menu does not open.

I noticed that a similar error appears not only for me, at least here is the same thing: https://github.com/Matoking/protontricks/issues/186#issuecomment-1331144016

**To Reproduce**
1. Go to SteamOS
2. Go to settings and change the language to Ukrainian
3. Go back to your desktop
4. Launch the protontricks app
5. Try to open any prefix. The app will just close and nothing else will happen.

**Expected behavior**
I want the application to work correctly in other languages

**System (please complete the following information):**
 - Distro: Steam OS
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.10.0, released on 27.11.2022
 - Steam version: 1669935636

**Additional context**
I tried to run the application through the console to see the errors, the result is in the screenshot.

![Screenshot_20221204_134837](https://user-images.githubusercontent.com/2458113/205492800-399ebad2-3861-4fc1-8c10-90bcbee148a1.png)

[protontricks.txt](https://github.com/Matoking/protontricks/files/10148567/protontricks.txt)

**Comment by Matoking** [comment] 2022-12-11 15:54
This looks like a duplicate of #186. The user was able to solve the issue by setting the regional settings back to En-US.

I haven't investigated this issue thoroughly yet, but it might be related to how SteamOS 3 handles locales.

**Comment by Romz24** [comment] 2022-12-11 16:35
> The user was able to solve the issue by setting the regional settings back to En-US.

Yes, this fixes the issue. But I want to use Ukrainian language instead of English. I have to change the language every time to use your program, it's very inconvenient.

**Comment by Matoking** [comment] 2022-12-19 17:19
I've looked into the issue some more, and it might be because SteamOS 3 does not provide the necessary files for locales besides `en_US.UTF-8`, which is what SteamOS 3 uses by default.

To confirm that, could you run the following commands **while your locale is Ukrainian** and print the results?

```
locale
locale -a
```

For comparison's sake, on my Arch install, it results in the following:

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

$ locale -a
locale -a
C
C.UTF-8
en_GB.utf8
en_US
en_US.iso88591
en_US.utf8
fi_FI.utf8
POSIX
```

**Closed** 2023-01-11 18:04 UTC

**Comment by Matoking** [comment] 2023-01-11 18:07
I've pushed a fix to master, and it will be included proper in a future release. This _should_ fix the issue going by the same problem and solution appearing for other applications on Steam Deck. The issue can be reopened if that's not the case, however.
