### ISSUE TITLE
Flatpak crashes on Steam Deck

### ISSUE THREAD

**Issue by iamPanka** [Matoking/protontricks#306] opened 2024-06-30 21:28 UTC
Hi, already read about a similar error error on [#253](https://github.com/Matoking/protontricks/issues/253), but the solutions proposed there don't work. Do you have any help? (PS. I have a microsd)

Anyway, after the message in the attached txt file, ProtonTricks crashes
[protontricks.txt](https://github.com/user-attachments/files/16046280/protontricks.txt)

**Comment by Matoking** [comment] 2024-06-30 21:30
Duplicate of #304.

**Closed by Matoking** 2024-06-30 21:30 UTC
