### ISSUE TITLE
Vcrun2017 wont install on steam deck

### ISSUE THREAD

**Issue by ZxSol** [Matoking/protontricks#154] opened 2022-06-14 08:21 UTC
**Describe the bug**
whenever either using the GUI or the command in the terminal, it fails to install

**To Reproduce**
1. attempt to install vcrun2017 through the GUI or through the command ` flatpak run com.github.Matoking.protontricks 6550 vcrun2017
2. gui error gives :"Working around wine bug 50894 -- Working around failing wusa.exe lookup via C:windowsSysNative". 

command gives this:
warning: Working around wine bug 50894 -- Working around failing wusa.exe lookup via C:\windows\SysNative
------------------------------------------------------
Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/wine winecfg -v winxp64
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
------------------------------------------------------
warning: Running /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/wineserver -w. This will hang until all wine processes in prefix=/home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx terminate
------------------------------------------------------
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
Executing cabextract -q --directory=/home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/temp/win32 /home/deck/.var/app/com.github.Matoking.protontricks/cache/winetricks/vcrun2017/vc_redist.x86.exe -F a10
Executing cabextract -q --directory=/home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/syswow64 /home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll
/home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/temp/win32/a10: WARNING; possible 16776 extra bytes at end of file.
/home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/syswow64/ucrtbase.dll: Permission denied
------------------------------------------------------
warning: Note: command cabextract -q --directory=/home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/syswow64 /home/deck/.local/share/Steam/steamapps/compatdata/6550/pfx/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll returned status 1. Aborting.

**Expected behavior**
vcrun2017 should install....

**Comment by Matoking** [comment] 2022-06-22 18:56
This appears to be a duplicate of #97 and a known issue on the Winetricks/cabextract side; the upstream issue is being tracked at Winetricks/winetricks#1648.

**Closed by Matoking** 2022-06-22 18:56 UTC
