### ISSUE TITLE
galliumnine install segfaults wine (proton experimental)

### ISSUE THREAD

**Issue by IlgazC** [Matoking/protontricks#100] opened 2021-04-25 19:30 UTC
Not sure if this is a protontricks bug or  wine (steam) bug. Happens on Sims 4 (steam) which benefits greatly from this module on intel gpu.

openSUSE Tumbleweed here with all gallium things installed (including 32bit)

Executing load_galliumnine 
Executing mkdir -p /home/ilgaz/.cache/winetricks/galliumnine
Executing cd /home/ilgaz/.cache/winetricks/galliumnine
Downloading https://github.com/iXit/wine-nine-standalone/releases/download/v0.8/gallium-nine-standalone-v0.8.tar.gz to /home/ilgaz/.cache/winetricks/galliumnine
Executing cd /home/ilgaz
Executing rm -rf /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine
Executing mkdir -p /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine
Executing tar -C /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine --strip-components=1 -zxf /home/ilgaz/.cache/winetricks/galliumnine/gallium-nine-standalone-v0.8.tar.gz
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/lib32/d3d9-nine.dll.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/syswow64/d3d9-nine.dll
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/bin32/ninewinecfg.exe.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/syswow64/ninewinecfg.exe
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/lib64/d3d9-nine.dll.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/system32/d3d9-nine.dll
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/bin64/ninewinecfg.exe.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/system32/ninewinecfg.exe
Executing rm -rf /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine
Executing /home/ilgaz/.cache/protontricks/proton/Proton Experimental/bin/wine ninewinecfg -e
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
/home/ilgaz/.cache/protontricks/proton/Proton Experimental/bin/wine: line 70:  4993 Segmentation fault      (core dumped) "$PROTON_DIST_PATH"/bin/wine "$@"
------------------------------------------------------
warning: Note: command /home/ilgaz/.cache/protontricks/proton/Proton Experimental/bin/wine ninewinecfg -e returned status 139. Aborting.
------------------------------------------------------

**Comment by Matoking** [comment] 2021-04-26 17:33
You can try running the command with `--no-bwrap` and `-v` flags to check if bwrap containerization might be to blame. Make sure they're placed before the app ID and the `--gui` flag; for example, if you ran the command `protontricks 12340 --gui`, run `protontricks -v --no-bwrap 12340 --gui` instead.

If the problem still occurs, the issue is probably related to Proton instead of Protontricks.

**Comment by IlgazC** [comment] 2021-04-26 18:32
Thanks for caring. It seems like a proton bug. I had the same error with --no-bwrap option. Pasting Terminal output.    There  also     seems to be a mysterious lag between gui prompts.

ilgaz@hp:~> protontricks -v --no-bwrap --gui 
protontricks (INFO): Found Steam directory at /home/ilgaz/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/ilgaz/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: ilgazc
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton Experimental
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/ilgaz/.cache/protontricks/proton/Proton Experimental/bin
protontricks (INFO): Attempting to run command [PosixPath('/usr/bin/winetricks'), '--gui']
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/ilgaz/.steam/steam/steamapps/compatdata/1222670
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: b0bba0921c5fb2984a1f85920bfbf62a0a4922353468c295a702a7158d17c295 with wine-6.3 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call galliumnine
Executing mkdir -p /home/ilgaz/.steam/steam/steamapps/compatdata/1222670
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_galliumnine 
Executing rm -rf /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine
Executing mkdir -p /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine
Executing tar -C /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine --strip-components=1 -zxf /home/ilgaz/.cache/winetricks/galliumnine/gallium-nine-standalone-v0.8.tar.gz
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/lib32/d3d9-nine.dll.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/syswow64/d3d9-nine.dll
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/bin32/ninewinecfg.exe.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/syswow64/ninewinecfg.exe
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/lib64/d3d9-nine.dll.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/system32/d3d9-nine.dll
Executing mv /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine/bin64/ninewinecfg.exe.so /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/system32/ninewinecfg.exe
Executing rm -rf /home/ilgaz/.steam/steam/steamapps/compatdata/1222670/pfx/dosdevices/c:/windows/temp/galliumnine
Executing /home/ilgaz/.cache/protontricks/proton/Proton Experimental/bin/wine ninewinecfg -e
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
/usr/bin/winetricks: line 566: 26260 Segmentation fault      (core dumped) "$@"
------------------------------------------------------
warning: Note: command /home/ilgaz/.cache/protontricks/proton/Proton Experimental/bin/wine ninewinecfg -e returned status 139. Aborting.

**Comment by Matoking** [comment] 2021-04-29 15:17
Looks like the issue is not related to Protontricks; I'll close the issue for now.

The lag between GUI prompts might be related to startup time each time `wine` is called. It can be especially noticeable when bwrap is in use, as the container has to be initialized every time Winetricks performs a `wine` command. There has been some effort to optimize this in the Steam Runtime side of things, but it's unlikely to be as fast as using Winetricks with system Wine.

**Closed by Matoking** 2021-04-29 15:17 UTC

**Comment by Arndorferd** [comment] 2021-07-25 07:34
Getting this issue still on both winetricks and protontricks, I submitted a bug report to wine https://bugs.winehq.org/enter_bug.cgi

**Comment by Arndorferd** [comment] 2021-07-25 23:03
They are claiming that this isn't a wine issue, can someone tell me where to report this. I can only find the galliumnine standalone git and I would assume thats not the same as the packages that are installed in protontricks or am I wrong? Who's responsibility is this bug, if its wine could someone from here comment on the bug report I added to wine.

> Looks like the issue is not related to Protontricks; I'll close the issue for now.
> 
> The lag between GUI prompts might be related to startup time each time `wine` is called. It can be especially noticeable when bwrap is in use, as the container has to be initialized every time Winetricks performs a `wine` command. There has been some effort to optimize this in the Steam Runtime side of things, but it's unlikely to be as fast as using Winetricks with system Wine.
