### ISSUE TITLE
Setting STEAM_DIR makes it unable to find config.vdf and appcache.vdf

### ISSUE THREAD

**Issue by gcaliber** [Matoking/protontricks#19] opened 2019-05-18 21:28 UTC
If you use a steam library path for games outside the normal steam path it still needs to look in the default steam path for config.vdf and appcache.vdf. Current behavior cannot find compatdata without setting STEAM_DIR but can't find these files if is set since they are located in the default steam directory.

**Comment by Matoking** [comment] 2019-05-19 10:05
I've pushed a potential bug fix to the steam_root_fix branch. If you have installed protontricks using pipx the following should let you install it:

`pipx install --force --spec git+https://github.com/Matoking/protontricks.git@steam_root_fix protontricks`

---

If the fix doesn't work, please provide further details:

* What value are you using for `STEAM_DIR`?
* Does that directory contain the directories `appcache`, `config`, `steamapps`, `ubuntu12_32` and optionally `compatibilitytools.d`?
* If some of the directories don't exist, do they exist somewhere else, such as `STEAM_DIR/../.root`?

**Comment by gcaliber** [comment] 2019-05-21 01:20
I have it installed via AUR and haven't tested the fix yet.

I have STEAM_DIR set to /home/user/games/steamapps/ since this is where the games data is located and if I don't set it then protontricks fails to find any games.  The config.vdf is located at the default steam library directory, /home/user/.steam/steam/steamapps/

**Comment by Matoking** [comment] 2019-05-21 09:59
> I have it installed via AUR and haven't tested the fix yet.
> 
> I have STEAM_DIR set to /home/user/games/steamapps/ since this is where the games data is located and if I don't set it then protontricks fails to find any games. The config.vdf is located at the default steam library directory, /home/user/.steam/steam/steamapps/

That's weird, Protontricks should find all the library folders automatically if Steam is installed in the default location.

Could you check the contents of `/home/user/.steam/steam/steamapps/libraryfolders.vdf` or if the file exists in the first place? The contents should look like this:

```
"LibraryFolders"
{
	"TimeNextStatsReport"		"1558451506"
	"ContentStatsID"		"7825075166457755736"
	"1"		"/home/user/games"
}
```

In addition, could you run a search operation such as `protontricks -v -s <game name>` **without STEAM_DIR being set** and check what output it gives? You don't need to install the bug fix branch for this.

**Comment by Matoking** [comment] 2019-05-29 16:39
Have you tried the instructions in the previous comment? If you've fixed the issue, please let me know so I can close this issue.

**Comment by Matoking** [comment] 2019-06-04 16:44
Closing this issue due to inactivity.

**Comment by fuzunspm** [comment] 2019-06-14 19:09
is this merged with 1.2.2 or should i try with steam_root_fix branch?

**Comment by Matoking** [comment] 2019-06-15 08:54
> is this merged with 1.2.2 or should i try with steam_root_fix branch? Also please guide me to fix the issue. I have 2 install folders and having the same error message on non-default one on my external hdd

You can try the steam_root_fix branch per the instructions above to see if it helps.

If that doesn't work, could you check whether a file called `/home/USER/.steam/steam/steamapps/libraryfolders.vdf` exists, and if it does, what its contents are?

**Comment by vyrus714** [comment] 2019-08-04 04:08
I'm currently trying protontricks for the first time and ran into this issue.

/home/vyrus/.local/share/Steam/steamapps/libraryfolders.vdf:
> "LibraryFolders"
> {
> 	"TimeNextStatsReport"		"1565088048"
> 	"ContentStatsID"		"5251010062882613510"
> 	"1"		"/media/Data2/steam"
> 	"2"		"/media/Data/Games/SteamNix"
> }
> 

verbose game search output:
> [vyrus@TNM-ARCH ~]$ protontricks -v -s arma_3
> protontricks (INFO): Found Steam directory at /home/vyrus/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
> protontricks (INFO): Using default Steam Runtime at /home/vyrus/.steam/root/ubuntu12_32/steam-runtime
> protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
> protontricks (INFO): Found 2 Steam library folders
> protontricks (INFO): Skipping empty appmanifest /media/Data2/steam/steamapps/appmanifest_222880.acf
> Found no games.
> 
> NOTE: A game must be launched at least once before protontricks can find the game.
> [vyrus@TNM-ARCH ~]$ 

I modified the aur PKGBUILD to use the commit in the steam_root_fix branch you mentioned above and tried the command again, and with the steam directory set.

> [vyrus@TNM-ARCH protontricks-git]$ protontricks -V
> protontricks (1.2.1+5.g0722905)
> [vyrus@TNM-ARCH protontricks-git]$ protontricks -v -s arma_3
> protontricks (INFO): Found Steam directory at /home/vyrus/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
> protontricks (INFO): Using default Steam Runtime at /home/vyrus/.steam/root/ubuntu12_32/steam-runtime
> protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
> protontricks (INFO): Found 2 Steam library folders
> Found no games.
> 
> NOTE: A game must be launched at least once before protontricks can find the game.
> [vyrus@TNM-ARCH protontricks-git]$ STEAM_DIR=/media/Data/Games/SteamNix protontricks -v -s arma_3
> protontricks (ERROR): $STEAM_DIR was provided but didn't point to a valid Steam installation.
> Steam installation directory could not be found.
> [vyrus@TNM-ARCH protontricks-git]$

In the end I still wasn't able to get it working. Hope this helps, I'll check back if you need me to try any more commands.

**Comment by Matoking** [comment] 2019-08-04 07:33
> I'm currently trying protontricks for the first time and ran into this issue.
> 
> /home/vyrus/.local/share/Steam/steamapps/libraryfolders.vdf:
> 
> > "LibraryFolders"
> > {
> > "TimeNextStatsReport"		"1565088048"
> > "ContentStatsID"		"5251010062882613510"
> > "1"		"/media/Data2/steam"
> > "2"		"/media/Data/Games/SteamNix"
> > }
> 
> verbose game search output:
> 
> > [vyrus@TNM-ARCH ~]$ protontricks -v -s arma_3
> > protontricks (INFO): Found Steam directory at /home/vyrus/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
> > protontricks (INFO): Using default Steam Runtime at /home/vyrus/.steam/root/ubuntu12_32/steam-runtime
> > protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
> > protontricks (INFO): Found 2 Steam library folders
> > protontricks (INFO): Skipping empty appmanifest /media/Data2/steam/steamapps/appmanifest_222880.acf
> > Found no games.
> > NOTE: A game must be launched at least once before protontricks can find the game.
> > [vyrus@TNM-ARCH ~]$
> 
> I modified the aur PKGBUILD to use the commit in the steam_root_fix branch you mentioned above and tried the command again, and with the steam directory set.
> 
> > [vyrus@TNM-ARCH protontricks-git]$ protontricks -V
> > protontricks (1.2.1+5.g0722905)
> > [vyrus@TNM-ARCH protontricks-git]$ protontricks -v -s arma_3
> > protontricks (INFO): Found Steam directory at /home/vyrus/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
> > protontricks (INFO): Using default Steam Runtime at /home/vyrus/.steam/root/ubuntu12_32/steam-runtime
> > protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
> > protontricks (INFO): Found 2 Steam library folders
> > Found no games.
> > NOTE: A game must be launched at least once before protontricks can find the game.
> > [vyrus@TNM-ARCH protontricks-git]$ STEAM_DIR=/media/Data/Games/SteamNix protontricks -v -s arma_3
> > protontricks (ERROR): $STEAM_DIR was provided but didn't point to a valid Steam installation.
> > Steam installation directory could not be found.
> > [vyrus@TNM-ARCH protontricks-git]$
> 
> In the end I still wasn't able to get it working. Hope this helps, I'll check back if you need me to try any more commands.

Did you try searching by using the command `protontricks -s arma 3` instead? Underscores are not ignored by Protontricks.

**Comment by vyrus714** [comment] 2019-08-04 14:50
I went back and tried both `arma` and `arma 3` on both branches but neither were able to find the game. It's a slightly unusual setup, since I have proton under my main\default steam directory under my home folder, which has the compat data, while the secondary game library is on another drive with the game's install folder. Using the main branch, without the vdf fix or the STEAM_DIR override, I checked some games that had both their data and compatdata in the same steam folder and was able to find them just fine. I also found another game I had with the two folders split and it was also not able to find that one, so it seems the issue is occurring when the compat and game data folders are separated.

**Comment by Matoking** [comment] 2019-08-07 16:00
> I went back and tried both `arma` and `arma 3` on both branches but neither were able to find the game. It's a slightly unusual setup, since I have proton under my main\default steam directory under my home folder, which has the compat data, while the secondary game library is on another drive with the game's install folder. Using the main branch, without the vdf fix or the STEAM_DIR override, I checked some games that had both their data and compatdata in the same steam folder and was able to find them just fine. I also found another game I had with the two folders split and it was also not able to find that one, so it seems the issue is occurring when the compat and game data folders are separated.

So, if I understand correctly, your game installation looks like this:

```
A/steamapps/common/Arma 3
B/steamapps/compatdata/107410
```

If so, does the file `appmanifest_107410.acf` exist under either `A/steamapps` or `B/steamapps`, and if so, what are its contents?

**Comment by vyrus714** [comment] 2019-08-08 18:21
Sorry if I was a bit long winded, but yea that's how the game is separated out.
The appmanifest is in the steam directory with the game data, so path A in your example.

pastebin: [appmanifest_107410.acf](https://pastebin.com/vpq4iSGK)

**Comment by Matoking** [comment] 2019-08-11 13:36
> Sorry if I was a bit long winded, but yea that's how the game is separated out.
> The appmanifest is in the steam directory with the game data, so path A in your example.
> 
> pastebin: [appmanifest_107410.acf](https://pastebin.com/vpq4iSGK)

I've pushed an update to `compatdata_fix` branch that should search for Proton prefixes correctly.

If you installed Protontricks using pipx, run the following command
```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@compatdata_fix protontricks
```

and check if it fixes the issue.

**Comment by Shados** [comment] 2019-08-17 10:17
@Matoking I ran into the same issue, the `compatdata_fix` branch fixes the issue for me.

**Comment by Matoking** [comment] 2019-08-17 14:25
> @Matoking I ran into the same issue, the `compatdata_fix` branch fixes the issue for me.

Thanks for the confirmation, I've merged the fix into master.

**Closed by Matoking** 2019-08-17 14:25 UTC
