### ISSUE TITLE
Crashes when selecting a steam app

### ISSUE THREAD

**Issue by MrCuriousCat** [Matoking/protontricks#311] opened 2024-07-07 00:23 UTC
**Describe the bug**
Crashes when selecting a steam app.

**To Reproduce**
1. Open protontricks
2. Select steam app
3. Error message appears

**Expected behavior**
No errors when selecting steam app.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.11.1
 - Steam version: Steam Families Beta 1719967667

**Additional context**

[Error Message](https://gist.github.com/MrCuriousCat/a1685cf8b28439589bd8bc93b81e0bed)

**Comment by Matoking** [comment] 2024-07-07 20:28
Duplicate of #304.

**Closed by Matoking** 2024-07-07 20:28 UTC
