### ISSUE TITLE
Protontricks uses wrong wine for winetricks when installing libs

### ISSUE THREAD

**Issue by Meister1593** [Matoking/protontricks#91] opened 2021-03-18 14:37 UTC
**Describe the bug**
When i use protontricks, i can open winecfg and see correct version for whatever game i  need, but when i want to install lib (for example, .net runtime 4.8), it uses my system wine for installing. 
Thus, i can't install some libraries that needs older version of wine (again, .net 4.8 is broken in wine 6.4)

**To Reproduce**
Needs system wine installation (on arch it's wine 6.4)
1. Run command `protontricks --gui`
2. Choose any game, hit OK
3. Log would produce something like this:
```
protontricks --gui
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/plyshka/.steam/steam/steamapps/compatdata/244850
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206 - sha256sum: fca9fc58fa48951cecf67b8d42aa6b947f90307a08415d9403d2b8913e03a1d7 with 6.4 and WINEARCH=win64
```
4. Try to install library that requires specific wine version (for example, dotnet48)

**Expected behavior**
It should not use system wine at all and only use proton that is specified for game. And libraries should be installed using that specific proton version.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks version: protontricks (1.4.4) [AUR
](https://aur.archlinux.org/packages/protontricks/) - Steam version: 
![image](https://user-images.githubusercontent.com/7141787/111643319-50bba700-8818-11eb-9c27-6182bcc1dbd4.png)

**Additional Notes**
For some reason, when i choose another game it starts using proper proton for winetricks
So, i'm not sure what is misbehaving here.

**Comment by Meister1593** [comment] 2021-03-18 14:44
I tried changing `config_info` file inside prefix folder (it had wrong proton specified inside), but it didn't help at all.

**Comment by Matoking** [comment] 2021-03-18 17:41
What does Protontricks say if you run the command `protontricks -v --gui` instead? What Proton version does Space Engineers use in your case? Is it the same as other game(s) mentioned in your notes?

You can try finding the corresponding Proton installation under your Steam library (make sure the "Tools" category is checked), then open Properties -> Local Files and click "Verify integrity of game files...".

Protontricks creates helper scripts under ~/.cache/protontricks/proton/<Proton name>` when using Steam Runtime. Those scripts might fail to work properly if they're out-of-date, in which case you can try to run `rm -rf ~/.cache/protontricks` and try running the command again. I'd expect the commands to fail outright instead of silently using system Wine instead, but it's worth a try.

One reason might be that you have `WINE` and `STEAM_RUNTIME=0` environment variable set globally (check this by running `env` outside of Protontricks). Not very likely to work if other games work properly, though.

The `config_info` file shouldn't have any effect on Protontricks.

**Comment by Meister1593** [comment] 2021-03-18 18:01
This is what happens before and after i removed cache for protontricks and i ran `protontricks -v --gui` on a space engineers prefix
```
protontricks (INFO): Found Steam directory at /home/plyshka/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/plyshka/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: meister1593
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton 5.0
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/plyshka/.cache/protontricks/proton/Proton 5.0/bin
protontricks (INFO): Attempting to run command [PosixPath('/usr/bin/winetricks'), '--gui']
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/plyshka/.steam/steam/steamapps/compatdata/244850
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206 - sha256sum: fca9fc58fa48951cecf67b8d42aa6b947f90307a08415d9403d2b8913e03a1d7 with 6.4 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
```

However, i just noticed that when i set Proton 5 to `Forts` is starts using system wine too...
```
protontricks (INFO): Found Steam directory at /home/plyshka/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/plyshka/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: meister1593
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton 5.0
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/plyshka/.cache/protontricks/proton/Proton 5.0/bin
protontricks (INFO): Attempting to run command [PosixPath('/usr/bin/winetricks'), '--gui']
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/plyshka/.steam/steam/steamapps/compatdata/410900
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206 - sha256sum: fca9fc58fa48951cecf67b8d42aa6b947f90307a08415d9403d2b8913e03a1d7 with 6.4 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
```

I checked file integrity for Proton 5.0, it's good with no issues

I don't have any env vars set globally that are related to wine or to steam (`env | grep -i wine`, `env | grep -i steam` (will show pwd but that's normal))

**Comment by Matoking** [comment] 2021-03-18 19:20
Try running the following command:

```
$ protontricks -c 'command -v wine' 244850
```

It should print the path to the Proton specific binary. If it's printing a path starting with `/usr/bin` or similar, something's probably wrong with Protontricks.

You can also try the running the following command (hopefully it still reproduces the issue despite being a bit different!):

```
$ protontricks -v 244850 --gui -v
```

This will print **a lot** more text, so you will probably want to post the output to [gist.github.com](https://gist.github.com) and link it here. There's a chance that Winetricks still picks the wrong Wine executable despite Protontricks configuring the environment otherwise.

**Comment by Meister1593** [comment] 2021-03-18 19:32
> Try running the following command:
> 
> ```
> $ protontricks -c 'command -v wine' 244850
> ```
> 
> It should print the path to the Proton specific binary. If it's printing a path starting with `/usr/bin` or similar, something's probably wrong with Protontricks.
> 
> You can also try the running the following command (hopefully it still reproduces the issue despite being a bit different!):
> 
> ```
> $ protontricks -v 244850 --gui -v
> ```
> 
> This will print **a lot** more text, so you will probably want to post the output to [gist.github.com](https://gist.github.com) and link it here. There's a chance that Winetricks still picks the wrong Wine executable despite Protontricks configuring the environment otherwise.

First command returned proper path (`/home/plyshka/.cache/protontricks/proton/Proton 5.0/bin/wine`)

Second is uploaded [here](https://gist.github.com/Meister1593/689b40c085a456b012cbd4044f33a652)
It also didn't open protontricks, it just hangs indefenitely after small amount of time

**Comment by Matoking** [comment] 2021-03-19 21:30
It seems like Winetricks is using the scripts Protontricks generated as expected, but `6.4` is still being reported as the version for some reason. It could be that although the correct `wine` binary is executed, but it loads the system-wide `libwine.so.1` shared library instead of the one provided by Proton.

Could you try running the following commands:

```
$ protontricks -c bash 244850
$ # New shell is opened. Run the following command inside it
$ strace -e trace=open,openat,execve wine --version 2>&1 | grep wine
```

You'll need strace. Since you're on Arch, `sudo pacman -S strace` should do the trick if you don't have it installed.

In my case, the following is printed, meaning both the correct `wine` and the Proton provided `libwine.so.1` are loaded as expected.

```
$ strace -e trace=open,openat,execve wine --version 2>&1 | grep wine
execve("/home/matoking/.cache/protontricks/proton/Proton 5.13/bin/wine", ["wine", "--version"], 0x7fff468a52a8 /* 84 vars */) = 0
openat(AT_FDCWD, "/home/matoking/.cache/protontricks/proton/Proton 5.13/bin/wine", O_RDONLY) = 3
execve("/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/bin/wine", ["/mnt/LinuxDataSSD_B/SteamLibrary"..., "--version"], 0x55fdd205a6e0 /* 84 vars */) = 0
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/i686/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/i686/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/i686/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/i686/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/bin/../lib/wine/ntdll.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
wine-5.13-789-gc14054e6923
```

**Comment by Meister1593** [comment] 2021-03-19 21:38
> It seems like Winetricks is using the scripts Protontricks generated as expected, but `6.4` is still being reported as the version for some reason. It could be that although the correct `wine` binary is executed, but it loads the system-wide `libwine.so.1` shared library instead of the one provided by Proton.
> 
> Could you try running the following commands:
> 
> ```
> $ protontricks -c bash 244850
> $ # New shell is opened. Run the following command inside it
> $ strace -e trace=open,openat,execve wine --version 2>&1 | grep wine
> ```
> 
> You'll need strace. Since you're on Arch, `sudo pacman -S strace` should do the trick if you don't have it installed.
> 
> In my case, the following is printed, meaning both the correct `wine` and the Proton provided `libwine.so.1` are loaded as expected.
> 
> ```
> $ strace -e trace=open,openat,execve wine --version 2>&1 | grep wine
> execve("/home/matoking/.cache/protontricks/proton/Proton 5.13/bin/wine", ["wine", "--version"], 0x7fff468a52a8 /* 84 vars */) = 0
> openat(AT_FDCWD, "/home/matoking/.cache/protontricks/proton/Proton 5.13/bin/wine", O_RDONLY) = 3
> execve("/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/bin/wine", ["/mnt/LinuxDataSSD_B/SteamLibrary"..., "--version"], 0x55fdd205a6e0 /* 84 vars */) = 0
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/i686/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/i686/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/tls/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/i686/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/i686/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/sse2/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/lib/libwine.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
> openat(AT_FDCWD, "/mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common/Proton 5.13/dist/bin/../lib/wine/ntdll.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
> wine-5.13-789-gc14054e6923
> ```

[Log](https://gist.github.com/Meister1593/7ade39779985752fd25dc36f064a52ec)
From what i can see, it tries every libwine it can find and fall backs to one that is working, which is system wine in my case.

**Comment by Matoking** [comment] 2021-03-19 21:48
So the directory `/home/plyshka/.steam/steam/steamapps/common/Proton 5.0/dist/lib` does exist, but it doesn't contain the `libwine.so.1` file? Is the installation directory same if you select Proton 5.0 in your Steam library, and then select *Properties* -> *Local Files* -> *Browse...*?

In my installation `libwine.so.1` is a symlink to `libwine.so.1.0` in the same directory. You can also go into Proton's installation directory and open `proton_dist.tar`; both `dist/lib/libwine.so.1` and `dist/lib/libwine.so.1.0` should be found inside it.

**Comment by Meister1593** [comment] 2021-03-19 21:54
> So the directory `/home/plyshka/.steam/steam/steamapps/common/Proton 5.0/dist/lib` does exist, but it doesn't contain the `libwine.so.1` file? Is the installation directory same if you select Proton 5.0 in your Steam library, and then select _Properties_ -> _Local Files_ -> _Browse..._?
> 
> In my installation `libwine.so.1` is a symlink to `libwine.so.1.0` in the same directory. You can also go into Proton's installation directory and open `proton_dist.tar`; both `dist/lib/libwine.so.1` and `dist/lib/libwine.so.1.0` should be found inside it.

Yes, i don't have any symlinks that would point to different libraries inside lib folder.
In dist folder, i do have these symlinks
And steam doesn't think it's bad or anything...

**Comment by Meister1593** [comment] 2021-03-19 21:59
Well, i think problem is found
I reinstalled Proton 5 completely and it re-extracted dist folder (when i tried launching game first time with proton) and it now correctly defines wine/proton version
I guess all of this could have been solved by Verify file integrity suite, if only it accounted for dist folder (it's extracted only after first game launch). Quite unusual situo...

**Comment by Matoking** [comment] 2021-03-19 22:05
Proton installation is unusual in that the `proton_dist.tar` archive is **not** extracted under `dist` until you launch a game using Proton for the first time. I'm guessing that's why Steam's "Verify file integrity" didn't notice this?

In any case, this looks like a bug with either Steam or Proton. Since the `libwine.so.1` filename is hardcoded in the executable, the same behavior (wrong `libwine.so.1` getting loaded) most likely would have occurred when playing games using that version of Proton as well, though that could have been hard to notice depending on the games you were playing.

If there are no other issues, you can close this issue.

**Closed** 2021-03-19 22:08 UTC

**Comment by Meister1593** [comment] 2021-03-19 22:10
Thanks for helping me out in that very specific situation)
I learned quite a bit about debugging applications under linux while was going through this issue
