### ISSUE TITLE
SyntaxError: Invalid file magic number

### ISSUE THREAD

**Issue by Wizacek** [Matoking/protontricks#329] opened 2024-08-19 10:36 UTC
Hi, I'm having an issue with protontricks. When i try to run 'protontricks 976890 d3dcompiler_47 d3dx9_43' or select any game in 'protontricks --gui' I get this message: 
protontricks (INFO): Found Steam directory at /home/radek/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/radek/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: raytv
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_protontricks.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

I'm using Linux Mint 21.2, protontricks (1.7.0), and I'm not using beta version of steam. The game I'm trying to fix is Hiden Deep. I'm not really sure what this command is supposed to do but i read about this on ProtonDB. Also I not even sure if this is right place to ask for help so if not sorry bothering you. I'm new to Linux environment so I could use some help. Thanks for answering.

**Comment by Matoking** [comment] 2024-08-20 17:06
Duplicate of #304, see [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for workaround.

Also, the Protontricks version your Linux Mint release is shipping seems to be fairly old (1.7.0 was released back in January 2022). You might have an easier time running the Flatpak version.

**Closed by Matoking** 2024-08-20 17:06 UTC
