### ISSUE TITLE
ProtonTricks refuses to launch on Steamdeck newly formatted and fresh OS install.

### ISSUE THREAD

**Issue by Traffalger** [Matoking/protontricks#229] opened 2023-05-09 18:56 UTC
On a newly reformatted SteamOS (steamdeck) ProtonTricks loads for 1-2 seconds then icon disappears.  I 

1. - Run ProtonTricks from the discover store results in crash
2. - Run ProtonTricks from applications menu results in crash
3.  - Attempt to run protontricks from Konsole results in it saying: command not found.  

**Expected behavior**
When launching Protontricks the program should load not crash.   

 - Distro: Steam OS 3.4.6
 - Protontricks installation method: Discover Store
 - Protontricks version: 1.10.3
 - Steam version: stable

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

Cannot run any commands from konsole as protontricks "command not found" error.

I have uninstalled, reinstalled, restarted, tried to do a flatpak repair and all of the results are the same.  ProtonTricks just refuses to load on my reformatted steamdeck.  I "had" protontricks running on the SD before I had to reimage it.  It worked without any issues whatsoever.  I really don't know why it would not be working.

**Comment by Matoking** [comment] 2023-05-10 16:27
Can you try running the following command using Konsole? If the graphical launch is failing for some reason this might explain why.

```
flatpak run com.github.Matoking.protontricks -v --gui
```

The Flatpak version doesn't work immediately using the `protontricks` command; instead you'll have to configure an alias as [documented here](https://github.com/Matoking/protontricks#flatpak-recommended).

**Comment by Traffalger** [comment] 2023-05-10 17:17
When I run this command I get:

bwrap: Can't make symlink at /var/run: File exists

I try to create the aliases like you mentioned above and nothing displays but another prompt.
close Konsole and restart run your command again.  same error as before.

**Comment by Matoking** [comment] 2023-05-15 16:12
This seems to be an issue related to Flatpak and not Protontricks specifically.

Have you added any filesystem overrides using Flatseal, or using the command-line? You can try temporarily removing them and checking if that solves the issue. 

A comment that might be helpful:

https://github.com/flatpak/flatpak/issues/2200#issuecomment-1380430681

**Comment by Matoking** [comment] 2023-05-16 16:43
@Tedi1997 That is likely a different issue. Or does the `flatpak run com.github.Matoking.protontricks --gui` crash with the `bwrap: Can't make symlink at /var/run: File exists` message, same as with @Traffalger? Your log appears to show Flatpak launching Protontricks properly up to the point where a graphical window should appear. Does the window (it should have the title "Protontricks" and look similar to the [screenshot on the Flathub page](https://flathub.org/apps/com.github.Matoking.protontricks)) appear for a split second and then disappear?

If the issue is happening with other Flatpak apps like Protonup-Qt, it might have something to do with X11 and/or Flatpak, though I can't say for sure, and it would be a bit beyond my knowledge. In any case, if it happens with multiple apps, you could search for the issue or report it on the [SteamOS issue tracker](https://github.com/ValveSoftware/SteamOS).

**Comment by Tedi1997** [comment] 2023-05-16 16:58
> 

Thanks for the quick reply. I have used protontricks before so I have a slight idea how it should work but sometimes it would take a bit to load so I thought it was doing its thing on the first time. 

Upon double clicking the app or rightclicking an exe and opening it with Protontricks, the logo on the taskbar shows for a couple seconds and dissapears but the page with the game names and numbers doesn't appear. On system monitor it shows as active which further backs what you say that it appears open. However nothing comes up on screen. The interesting thing is it only happens with only these two Flatpak apps and none other and the only common factor they have is part of the name haha.

I tried the command you gave and at first glance nothing happens, however trying to close it says there is a process running called bwrap.

I'll report it on the SteamOS issue tracker as well

**Comment by Traffalger** [comment] 2023-05-16 19:43
> 

Here is the gist output when I run that command:

https://gist.github.com/Traffalger/1e7d9f756c31a2718383baffade88017

Will be looking at the comment you linked as well.

**Comment by Traffalger** [comment] 2023-05-16 19:46
> @Tedi1997 That is likely a different issue. Or does the `flatpak run com.github.Matoking.protontricks --gui` crash with the `bwrap: Can't make symlink at /var/run: File exists` message, same as with @Traffalger? Your log appears to show Flatpak launching Protontricks properly up to the point where a graphical window should appear. Does the window (it should have the title "Protontricks" and look similar to the [screenshot on the Flathub page](https://flathub.org/apps/com.github.Matoking.protontricks)) appear for a split second and then disappear?
> 
> If the issue is happening with other Flatpak apps like Protonup-Qt, it might have something to do with X11 and/or Flatpak, though I can't say for sure, and it would be a bit beyond my knowledge. In any case, if it happens with multiple apps, you could search for the issue or report it on the [SteamOS issue tracker](https://github.com/ValveSoftware/SteamOS).

Just to chime in my issue does not have Protontricks showing up in the System monitor under applications or processes.

**Comment by Traffalger** [comment] 2023-05-16 20:10
> This seems to be an issue related to Flatpak and not Protontricks specifically.
> 
> Have you added any filesystem overrides using Flatseal, or using the command-line? You can try temporarily removing them and checking if that solves the issue. If not, try running
> 
> ```
> flatpak run -vv com.github.Matoking.protontricks --gui
> ```
> 
> which will probably print a _lot_ of output. You'll want to copy and paste that to [gist.github.com](https://gist.github.com/) and copy a link here.
> 
> A comment that might be helpful:
> 
> [flatpak/flatpak#2200 (comment)](https://github.com/flatpak/flatpak/issues/2200#issuecomment-1380430681)

After reading the comment you linked it does appear to be an issue with the /var/run to just /run.  I must have added var to my sd card location in flatseal.  

After removing the /var Protontricks runs once again.  

Thank you for your help.

**Comment by Tedi1997** [comment] 2023-05-18 08:10
@Matoking If its okay with you should I open a new issue tracker for my topic here as well as it seems to be more gui related

**Comment by Matoking** [comment] 2023-05-19 08:06
Closing this since the original issue was solved.

**Closed by Matoking** 2023-05-19 08:06 UTC

**Comment by Traffalger** [comment] 2023-05-19 13:11
> Closing this since the original issue was solved.

Thank you, I wasn’t sure if I could close it or not.  Appreciate the help.
