### ISSUE TITLE
"traceback" & "running inside Flatpak Sandbox" error

### ISSUE THREAD

**Issue by Ametrine504** [Matoking/protontricks#341] opened 2024-09-12 14:50 UTC
Not sure why but I get these error messages when trying to open a game in protontricks (steam deck)

![PXL_20240912_061455354](https://github.com/user-attachments/assets/5c59c7c6-2181-4bb3-b29b-736c225a99a6)
![PXL_20240912_061455354](https://github.com/user-attachments/assets/9b98019a-fc8c-466b-97d5-5c44061ff624)

**Comment by Matoking** [comment] 2024-09-12 16:23
Duplicate of #304, see [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for workaround.

**Closed as completed by Matoking** 2024-09-12 16:23 UTC
