### ISSUE TITLE
Protontricks with Steam Snap package: Steam installation directory could not be found

### ISSUE THREAD

**Issue by dziadulewicz** [Matoking/protontricks#353] opened 2024-10-19 12:35 UTC
Trying to launch Protontricks in Ubuntu with Steam's snap package gives only: 

"Protontricks was closed due to the following error:

Steam installation directory could not be found.

=============

Please include this entire error message when making a bug report.
Log messages: 

"
And closes. 

The location of the snap version of Steam (with games) would be something like ~/snap/steam/common/.local/share/Steam/steamapps/common/Escape from Monkey Island
![Kuvakaappaus - 2024-10-19 15-30-22](https://github.com/user-attachments/assets/16c733c2-bfaa-43d0-9336-0e13ed47761d)

**Comment by KINGSHIGGY1122** [comment] 2024-10-20 12:04
I have the same issue, looking for a solution now.

**Comment by KINGSHIGGY1122** [comment] 2024-10-20 21:23
You need to install the .deb version of steam to fix this issue. The version of steam from the ubuntu discovery app isnt recognized by protontricks. https://customer.acecloudhosting.com/index.php/knowledgebase/232/How-to-Install-Steam-on-Ubuntu-20.04-.html?language=danish   Heres a link for instructions to install the correct steam

**Comment by Matoking** [comment] 2024-10-22 16:24
Protontricks 1.12.0 should support Steam Snap installations, have you checked that the newest version is installed?

If not, try running again with `protontricks -vv --gui` and posting the output.

**Comment by dziadulewicz** [comment] 2024-10-30 14:58
> Protontricks 1.12.0 should support Steam Snap installations, have you checked that the newest version is installed?
> 
> If not, try running again with `protontricks -vv --gui` and posting the output.

The version (.deb) of Protontricks available in Ubuntu is 1.10.5-1... :/ Could you possibly create a simple snap package at some point, please?

**Comment by Matoking** [comment] 2024-11-05 17:22
Sorry, I don't use Ubuntu and maintaining a Snap version of Protontricks would increase the maintenance workload. You can look into either the Flatpak version of Protontricks or the `pipx` installation option detailed in the README.

I'll close this issue, as the root cause seems to be an outdated installation of Protontricks.

**Closed by Matoking** 2024-11-05 17:22 UTC
