### ISSUE TITLE
StopIteration exception when running any commands

### ISSUE THREAD

**Issue by PandaTheRed** [Matoking/protontricks#88] opened 2021-02-03 12:51 UTC
When trying to run any command involving the compatdata folder for a particular game, such as `protontricks -c 'wine64 uninstaller' 359320` or selecting a game's folder in the GUI, the program fails with this message:

```
protontricks (INFO): Found Steam directory at /home/jack/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/jack/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: **********
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton 5.13
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/jack/.cache/protontricks/proton/Proton 5.13/bin
Traceback (most recent call last):
  File "/home/jack/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/jack/.local/pipx/venvs/protontricks/lib/python3.9/site-packages/protontricks/cli.py", line 267, in main
    run_command(
  File "/home/jack/.local/pipx/venvs/protontricks/lib/python3.9/site-packages/protontricks/util.py", line 219, in run_command
    get_runtime_library_paths(steam_runtime_path, proton_app)
  File "/home/jack/.local/pipx/venvs/protontricks/lib/python3.9/site-packages/protontricks/util.py", line 62, in get_runtime_library_paths
    runtime_root = next(
StopIteration

```
The program runs successfully when, in the util.py file, the following at line 61
```
runtime_root = next(
            proton_app.required_tool_app.install_path.glob("*/files/")
        )
```
is replaced with:
```
runtime_root = proton_app.required_tool_app.install_path
```

**Comment by Matoking** [comment] 2021-02-03 16:58
Closing, duplicate of #87.

**Closed by Matoking** 2021-02-03 16:58 UTC
