### ISSUE TITLE
Following Error when trying to start program after Update

### ISSUE THREAD

**Issue by Jashinthedevil** [Matoking/protontricks#310] opened 2024-07-03 10:30 UTC
**Describe the bug**
Launches, allows me to select game, then crashes with error message.

**To Reproduce**
1. Launch Protontricks
2. Select Game

**Expected behavior**
Program launches

**System (please complete the following information):**
 - Distro: SteamOS 3.5.17
 - Protontricks installation method: tried Flatpak and Discover
 - Protontricks version: 1.11.1
 - Steam version: Steam Deck Beta

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/deck/.local/share/Steam
Found 1 Steam library folders
Currently logged-in Steam user: j4shin
Found 1 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
Calling `protontricks` with the command: ['--no-background-wineserver', '--no-term', '-c', 'wine /home/deck/Desktop/Aurora/Aurora.exe', '1868140']
Running inside Flatpak sandbox, version 1.14.4.
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: j4shin
Found 1 Steam shortcuts running using Steam compatibility tools

**Comment by dennisw100** [comment] 2024-07-03 16:10
I have this error too

    Distro: Pop!_OS 22.04 LTS
    Protontricks installation method: Pop!_Shop which has flatpack and ubuntu deb both have the error
    Protontricks version: 1.11.1
    Steam version: Steam Beta Update 1719967667

**Comment by Matoking** [comment] 2024-07-04 07:37
Duplicate of #304

**Closed by Matoking** 2024-07-04 07:37 UTC
