### ISSUE TITLE
Keep getting this error no matter what

### ISSUE THREAD

**Issue by Sneedson** [Matoking/protontricks#319] opened 2024-07-15 19:09 UTC
Hello, every time I install and launch protontricks, I get this error. After I select a game and run it, this error happens. I have tried updating, installing with pipx, everything. Nothing seems to work. Please help me ASAP. 

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.7.
Found Steam directory at /home/skrinax/.local/share/Steam
Using default Steam Runtime at /home/skrinax/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 3 Steam library folders
Currently logged-in Steam user: kongregatespartan
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider

**Comment by Matoking** [comment] 2024-07-17 07:38
Duplicate of #304. See [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for a workaround.

**Closed by Matoking** 2024-07-17 07:38 UTC
