### ISSUE TITLE
Winecfg not launching

### ISSUE THREAD

**Issue by patmann03** [Matoking/protontricks#145] opened 2022-04-27 01:41 UTC
**Describe the bug**
Winecfg not launching when selecting from the GUI or in terminal

**To Reproduce**
1. Open the Protontricks GUI
2. Select the default prefix
3. Select winecfg and hit ok

**Expected behavior**
winecfg would launch and I could set library overrides if desired.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks installation method: AUR
 - Protontricks version: 1.8.1
 - Steam version: Yes, running the latest Steam Beta

**Additional context**
I can open winecfg by:

WINEPREFIX=/PATH/TO/PFX winecfg

```
protontricks -v -c  winecfg 214950 >> protontricks.log
protontricks (INFO): Found Steam directory at /home/patrick/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/patrick/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 3 Steam library folders
protontricks (INFO): Currently logged-in Steam user: <REDACTED>
protontricks (INFO): Found 0 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): User has configured app Proton version (CompatToolMapping): GE-Proton7-15
protontricks (INFO): User has configured default Proton version (CompatToolMapping): proton_7
protontricks (INFO): Found active custom compatibility tool: GE-Proton7-15
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/patrick/.cache/protontricks/proton/GE-Proton7-15/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Starting bwrap launcher process: /home/patrick/.cache/protontricks/proton/GE-Proton7-15/bin/bwrap-launcher
protontricks (INFO): Starting wineserver keepalive process: /home/patrick/.cache/protontricks/proton/GE-Proton7-15/bin/wineserver-keepalive
protontricks (INFO): Attempting to run command winecfg
protontricks - bwrap-launcher 33106: Following directories will be mounted inside container: /boot /cnijfilter2-5.40-1-rpm /efi /etc /home /lost+found /mnt /opt /root /sbin /scangearmp2-3.40-1-rpm /srv /tmp /run/media
protontricks - wineserver-keepalive 33107: Starting wineserver-keepalive process...
protontricks - bwrap-launcher 33106: Using temporary directory: /tmp/protontricks-apqdcke3
protontricks - wine 33108: Checking for running wineserver instance
protontricks - wine 33108: Setting default env: WINEFSYNC=1
protontricks - wine 33108: Setting default env: WINEESYNC=1
protontricks - wine 33108: Starting Wine process using 'pressure-vessel-launch'
protontricks - wine 33108: bwrap-launcher socket not yet available, waiting...
protontricks - wine 33325: Starting Wine process inside the container
protontricks - wine 33325: Appending to LD_LIBRARY_PATH: /home/patrick/.steam/root/compatibilitytools.d/GE-Proton7-15/files/lib:/home/patrick/.steam/root/compatibilitytools.d/GE-Proton7-15/files/lib64:
0034:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
0034:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
Authorization required, but no authorization protocol specified
00e8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00e8:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
00e8:err:systray:initialize_systray Could not create tray window
012c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
012c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
012c:err:tabtip:wWinMain Failed to create hwnd!
0138:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0138:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
protontricks (INFO): Terminating wineserver keepalive process 33107
protontricks (INFO): Terminating launcher process 33106
protontricks (INFO): Launcher process terminated
protontricks - wineserver-keepalive 33107: Cleanup finished, goodbye!
```

**Comment by patmann03** [comment] 2022-04-27 02:58
This may be the same issue as: #142.  If I add the flag --no-bwrap it launches no problem.  

My DE is KDE Plasma, running wayland session.

**Comment by Matoking** [comment] 2022-05-03 20:02
I was able to reproduce this in my environment, and it appears to be due to Steam Runtime passing the `XAUTHORITY` and `DISPLAY` environment variables directly to the sandbox without changing them properly. Any commands that should result in X11 windows appearing would then fail.

I've pushed a fix to the `fix_xauthority_crash` branch. You can test it by installing it using pipx like so:

```
pipx install --force git+https://github.com/Matoking/protontricks.git@fix_xauthority_crash
```

Does the fix solve the issue, or does `winecfg` still fail to appear?

**Comment by Ifropc** [comment] 2022-05-06 05:19
@Matoking Hi, I confirm that this fix works for me. Thanks a lot!

**Closed** 2022-05-07 14:37 UTC

**Comment by Matoking** [comment] 2022-05-07 14:39
Thanks for confirming that the fix works. I've pushed the fix to master.

I'll look into releasing a new version once I've resolved another pending issue. For now, installing the development version should work for those facing the same issue.
