### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by lyghters** [Matoking/protontricks#31] opened 2019-10-06 20:35 UTC
I'm having this error when launching Protontricks with GUI on Arch Linux:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/protontricks/gui.py", line 27, in select_steam_app_with_gui
    ], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zenity', '--forms', '--text=Steam Game Library', '--title=Choose Game', '--add-combo', 'Pick a library game', '--combo-values', 'Cube World: 1128000|EVE Online: 8500|Infinity: Battlescape: 1079620|NEOTOKYO��: 244630|Quake Live: 282440|Serious Sam 2: 204340|TEKKEN 7: 389730|Tabletop Simulator: 286160']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 11, in <module>
    load_entry_point('protontricks==1.2.5', 'console_scripts', 'protontricks')()
  File "/usr/lib/python3.7/site-packages/protontricks/cli.py", line 174, in main
    steam_app = select_steam_app_with_gui(steam_apps=steam_apps)
  File "/usr/lib/python3.7/site-packages/protontricks/gui.py", line 48, in select_steam_app_with_gui
    raise RuntimeError("Zenity returned an error")
RuntimeError: Zenity returned an error
```

Any suggestions? Or info you need me to post here?

**Comment by Matoking** [comment] 2019-10-07 14:45
Run the following commands to check the versions for both Protontricks and Zenity:
```
zenity --version
protontricks --version
```

On top of that, could you tell me if running the command directly causes an error message or something else to happen:
```
zenity --forms --text='Steam Game Library' --title='Choose Game' --add-combo 'Pick a library game' --combo-values 'Cube World: 1128000|EVE Online: 8500|Infinity: Battlescape: 1079620|NEOTOKYO��: 244630|Quake Live: 282440|Serious Sam 2: 204340|TEKKEN 7: 389730|Tabletop Simulator: 286160'
```

**Comment by lyghters** [comment] 2019-10-07 21:12
Hey, thank you for responding.
Zenity is 3.32.0, Protontricks 1.2.5.
I'm afraid I cannot copy-paste "��" into terminal, it might be a cause of the problem.

**Comment by JamesMConroy** [comment] 2019-10-12 03:52
I am having the same issue
Zentity 3.32.0
Protontricks (1.2.5+1.ga59d866)

When I copy and past the above command I get "This option is not available. Please see --help for all possible usages."

If I only run the command with the first two combo options I get a gui with no issues.

**Comment by Matoking** [comment] 2019-10-12 06:11
I've pushed a small change to *zenity_test* branch that prints a bit more information when the error occurs. Please try that branch and tell me if it prints anything new. I'm running the same version of Zenity, but I haven't been able to reproduce the error myself.

If Protontricks was installed using pipx, the following should work:

```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@zenity_test protontricks
```

**Comment by JamesMConroy** [comment] 2019-10-20 03:32
I get "b'This option is not available. Please see --help for all possible usages.\n'
b''" to stdout
and the following is sent to stderror 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/protontricks-1.2.5+2.gceb2407-py3.7.egg/protontricks/gui.py", line 27, in select_steam_app_with_gui
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zenity', '--forms', '--text=Steam Game Library', '--title=Choose Game', '--add-combo', 'Pick a library game', '--combo-values', 'DARK SOULS™: REMASTERED: 570940|Fallout: 38400|Fallout: New
Vegas: 22380|Prey: 480490|The Witcher 3: Wild Hunt: 292030|Underrail: 250520']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 11, in <module>
    load_entry_point('protontricks==1.2.5+2.gceb2407', 'console_scripts', 'protontricks')()
  File "/usr/lib/python3.7/site-packages/protontricks-1.2.5+2.gceb2407-py3.7.egg/protontricks/cli.py", line 174, in main
  File "/usr/lib/python3.7/site-packages/protontricks-1.2.5+2.gceb2407-py3.7.egg/protontricks/gui.py", line 50, in select_steam_app_with_gui
RuntimeError: Zenity returned an error

**Comment by Matoking** [comment] 2019-10-20 19:03
> When trying to launch the gui with that branch I get "b'This option is not available. Please see --help for all possible usages.\n'
> b''" to stdout
> and the following is sent to stderror
> Traceback (most recent call last):
> File "/usr/lib/python3.7/site-packages/protontricks-1.2.5+2.gceb2407-py3.7.egg/protontricks/gui.py", line 27, in select_steam_app_with_gui
> File "/usr/lib/python3.7/subprocess.py", line 487, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['zenity', '--forms', '--text=Steam Game Library', '--title=Choose Game', '--add-combo', 'Pick a library game', '--combo-values', 'DARK SOULS™: REMASTERED: 570940|Fallout: 38400|Fallout: New
> Vegas: 22380|Prey: 480490|The Witcher 3: Wild Hunt: 292030|Underrail: 250520']' returned non-zero exit status 255.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/bin/protontricks", line 11, in
> load_entry_point('protontricks==1.2.5+2.gceb2407', 'console_scripts', 'protontricks')()
> File "/usr/lib/python3.7/site-packages/protontricks-1.2.5+2.gceb2407-py3.7.egg/protontricks/cli.py", line 174, in main
> File "/usr/lib/python3.7/site-packages/protontricks-1.2.5+2.gceb2407-py3.7.egg/protontricks/gui.py", line 50, in select_steam_app_with_gui
> RuntimeError: Zenity returned an error
> 
> Proton tricks is version 1.2.5+2.gceb2407

I have Zenity 3.32.0 installed as well, but I have no problems running the command either through Protontricks or directly.

I noticed that non UTF-8 locale seems to cause the "option not available" message when unusual characters are in the command. Can you run the command `locale` and submit the output? In my case, it prints:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

You could also try whether you can run the first command but not the second one:

```
zenity --forms --text='Steam Game Library' --title='Choose Game' --add-combo 'Pick a library game' --combo-values 'Infinity: Battlescape: 1079620|NEOTOKYO��: 244630'
zenity --forms --text='Steam Game Library' --title='Choose Game' --add-combo 'Pick a library game' --combo-values 'Infinity: Battlescape: 1079620|NEOTOKYO: 244630'
```

**Comment by sonic2kk** [comment] 2019-12-24 18:36
The issue indeed comes from locales. Using Arch I only set en_GB locales, and had to set en_US locales. You can do this by exiting `/etc/locale.gen` as root and uncommenting `en_US.UTF-8` and the ISO variant of this locale.

For users that don't want to do this, I've submitted a pull request that removes Unicode symbols from the game strings.

**Comment by Matoking** [comment] 2020-01-01 15:18
A fix has been pushed to master.

Protontricks can work around this issue by removing the problematic characters that the locale can't handle. I recommend changing the locale to use UTF-8 instead (eg. `en_US.UTF-8`), since it can handle non-English characters and will likely prevent similar issues down the road not only limited to Protontricks.

As far as I know, most Linux distros should use UTF-8 locales out-of-the-box and distros that allow the user to choose such as Arch recommend UTF-8, so the unusual locale might be in use due to some other issue.

**Closed by Matoking** 2020-01-01 15:18 UTC
