### ISSUE TITLE
Cannot install dotnet48 on Steam Deck

### ISSUE THREAD

**Issue by LiamDawe** [Matoking/protontricks#179] opened 2022-10-23 12:28 UTC
**Describe the bug**
Unable to install dotnet48, it goes through the installer UI and then says install failed.

**To Reproduce**

- Run it via the UI
- Select default prefix
- Try to install dotnet48 on Steam Deck

**Expected behavior**
It installs. 

**System (please complete the following information):**
 - Distro: SteamOS
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.9.2
 - Steam version: Oct 21 - 1666399660

**Additional context**

Error log: https://gist.github.com/LiamDawe/83e7c88b6ca491e8206eff4cd47571a6

**Comment by Matoking** [comment] 2022-10-25 15:58
This issue seems to be a duplicate of #157. .NET 4 is broken on Wine/Proton 5 or newer.

You could try creating a new prefix on an older Proton version, installing .NET 4 there and then changing the Proton version to a newer one.

**Closed by Matoking** 2022-10-25 15:58 UTC
