### ISSUE TITLE
protontricks -c "env" 261550 | grep "WINEPREFIX" does not work.

### ISSUE THREAD

**Issue by mrdarwinjs** [Matoking/protontricks#323] opened 2024-07-23 15:37 UTC
**Describe the bug**
command dont work

**To Reproduce**
1. Run command `protontricks -c "env" 261550 | grep "WINEPREFIX"`
2. Command fails and error is displayed

**Expected behavior**
to work protontricks of course.

**System (please complete the following information):**
 - Distro: endeavouros
 - ArchLinux:AUR
 - Protontricks version: protontricks (1.11.1)
 - Steam version: 

error code: 
protontricks -c "env" 261550 | grep "WINEPREFIX"
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

**Comment by SecularSteve** [comment] 2024-07-25 15:58
Much of the same here with my Steam Deck OLED/SteamOS Latest Beta.

Except now it won't launch when opening it from the Start Menu/GUI.

This pops out every time I try to open a game:

`
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.6.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 4 Steam library folders
Steam library folder /run/media/deck/ae1e05bf-c90b-427e-a5a1-8505e09f8659 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/deck/0fa7597c-3b0d-4f20-89c0-0f197dbcbef1 not found. Protontricks might not have access to the directory.
Currently logged-in Steam user: sam9984
Shortcut Microsoft Edge (4144478434) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut RetroDECK (2778338588) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kodi (3868922086) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Firefox webbrowser (2579942389) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sonic Robo Blast 2 (3935396741) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Dr. Robotnik's Ring Racers (4063712601) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut GZDoom (2518238172) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Clone Hero (3367518170) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 1 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
`

**Comment by mrdarwinjs** [comment] 2024-07-26 15:36
Similarly same error.

**Comment by Matoking** [comment] 2024-07-29 16:29
Duplicate of #304, see [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for workaround.

**Closed by Matoking** 2024-07-29 16:29 UTC
