### ISSUE TITLE
protontricks error

### ISSUE THREAD

**Issue by Kilgorio** [Matoking/protontricks#313] opened 2024-07-12 19:31 UTC
I get this error when selecting cities skylines 2 that wasn't there before
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/emi/.local/share/Steam
Using default Steam Runtime at /home/emi/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 4 Steam library folders
Multiple compatdata directories found for app 949230
Steam library folder /mnt2/Steam not found. Protontricks might not have access to the directory.
Steam library folder /run/media/emi/GAMES/Steam not found. Protontricks might not have access to the directory.
Multiple compatdata directories found for app 949230
Currently logged-in Steam user: kilgorio
Shortcut Cities2.exe (2159992616) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider

**Comment by Kilgorio** [comment] 2024-07-12 19:32
also happens in other games

**Comment by Matoking** [comment] 2024-07-17 07:47
Duplicate of #304. See [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for a workaround.

**Closed by Matoking** 2024-07-17 07:47 UTC
