### ISSUE TITLE
Crashing on Launch - Traceback

### ISSUE THREAD

**Issue by GatorMilkMerchant** [Matoking/protontricks#315] opened 2024-07-13 18:26 UTC
Hello! I don't know this site very well, and am not too tech literate, so forgive me for if this is a repeat that someone else has had. I use this PC, Linux Mint XFCE 21.3 for gaming and watching movies. I use the System Package of Steam and the Flatpak of Protontricks. 

**Describe the bug**
Up til recently, I have had 0 problems with Protontricks, and have been able to play even the most jank of games well enough. I wanted to play the new Brigand: Oaxaca moon map, and use the GOG version launched with Protontricks to play the game. Today, I received this error when attempting to play the game. Protontricks always knew I use the System Package of Steam, but now asks when I launch if I use the System Package or the Flatpak, after the first use of Protontricks last year when I first swapped over. I am about to try the 1.7 System package version. As far as I know, attempting to read and understand this log, Mint 21.3 has Python 3.10. I tried installing Python 3.11, and have no problems on my system, but the game will still give me the following same error window (pasted below all the required tags):

**To Reproduce**
1. Right-click the Brigand Oaxaca Desktop Shortcut.
2. Run with Protontricks Launcher
3. Select Steam System Package
4. Select the Brigand: Oaxaca preset
5. Get the error box popup

**Expected behavior**
To launch Brigand: Oaxaca

**System (please complete the following information):**
 - Distro: Linux Mint XFCE 21.3
 - Protontricks installation method: Flatpak; the System Package version nets the same results.
 - Protontricks version: 1.11.1; the System Package version nets the same results.
 - Steam version: Steam Beta Version (For Family Sharing)

**Additional context**
I have also tried Fossilfuel 2 and the demo of DEEP STATE, a goldeneye+Deus Ex inspired Itch.io game. Same error. :/

**If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**
For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -vv 42 faudio` instead and copy the output here.
If the output is very long, consider creating a gist using [gist.github.com](https://gist.github.com/).

I did not use a command, I used the GUI, and i don't know how to run the command for the flatpak version.

**********The Dialogue Box is as follows:**********
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/tristan/.steam/debian-installation
Found Steam directory at /home/tristan/.var/app/com.valvesoftware.Steam/.local/share/Steam
Using 'yad' as GUI provider
Found 1 Steam library folders
Currently logged-in Steam user: azzalack
Found 2 Steam shortcuts running using Steam compatibility tools
Calling `protontricks` with the command: ['--no-background-wineserver', '--no-term', '-c', 'wine /home/tristan/.steam/debian-installation/steamapps/common/Brigand/Brigand.exe', '652410']
Running inside Flatpak sandbox, version 1.12.7.
Using default Steam Runtime at /home/tristan/.steam/debian-installation/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: azzalack
Found 2 Steam shortcuts running using Steam compatibility tools

**Comment by Matoking** [comment] 2024-07-17 07:47
Duplicate of #304. See [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for a workaround.

**Closed by Matoking** 2024-07-17 07:47 UTC
