### ISSUE TITLE
Crash when selecting a game on Arch

### ISSUE THREAD

**Issue by vproper** [Matoking/protontricks#324] opened 2024-07-31 13:50 UTC
**Describe the bug**
Protontricks crashes when selecting a game

**To Reproduce**
1. Install Arch
2. Install protontricks
3. Select a game
4. Crash

**Expected behavior**
No crash

**System (please complete the following information):**
 - Distro: Arch
 - Protontricks installation method: AUR package, pipx
 - Protontricks version: protontricks (1.11.1)
 - Steam version: Betra
**Additional context**
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/home/vantuzproper/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vantuzproper/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/home/vantuzproper/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vantuzproper/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/home/vantuzproper/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/vantuzproper/.local/share/Steam
Using default Steam Runtime at /home/vantuzproper/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Steam library folder /ssd2/SteamLibrary not found. Protontricks might not have access to the directory.
Currently logged-in Steam user: bengboxer
Found 1 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider

**Comment by oldlamps** [comment] 2024-07-31 22:00
I'm receiving this same error in both this and the flatpak version on my EndeavourOS install.

**Comment by RunicLena** [comment] 2024-08-02 19:12
having the same issue on steam deck

**Comment by sTiKyt** [comment] 2024-08-03 13:58
Same problem on the latest version

**Comment by Matoking** [comment] 2024-08-04 08:41
Duplicate of #304, see [this comment](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470) for workaround.

**Closed by Matoking** 2024-08-04 08:41 UTC
