### ISSUE TITLE
KeyError: 'name' running protontricks

### ISSUE THREAD

**Issue by JPLeBreton** [Matoking/protontricks#103] opened 2021-05-28 05:32 UTC
**Describe the bug**
Any invocation of protontricks with any arguments, including `protontricks -v --gui` or `protontricks 1224290 d3dcompiler_47` (the game ID + command I'm trying to run) gives this error with verbose output enabled:
```
protontricks (INFO): Found Steam directory at /home/jpl/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/jpl/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Multiple compatdata directories found for app 275850
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.5.1', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 180, in main
    steam_apps = get_steam_apps(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 860, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 190, in from_appmanifest
    name = app_state["name"]
KeyError: 'name'
```

**To Reproduce**
1. Run `protontricks --gui`.

**System (please complete the following information):**
 - Distro: Manjaro Linux 64-bit (stable branch)
 - Protontricks version: 1.5.1 (from AUR)
 - Steam version: Steam build 2021-05-19, "package versions" 1621394999 (not running any betas)
 - Python version: 3.9 (the standard system version for this distro from official repos)

**Additional context**
All dependencies listed in the readme are installed.
To be clear, I am running the versions of Proton that are provided by the Steam client; ie I have not installed Proton from the package manager or compiled it myself.
I have a minimally configured Wine (and winetricks) installed on my system that I occasionally use for non-Steam applications but 99% of Windows stuff I run on the system is via Steam + Proton.

**Comment by Matoking** [comment] 2021-05-29 14:47
Try running the following command:

```
python -m pdb -c continue -m protontricks.cli -v --gui
```

The command should fail with the same error, but also launch a debugger. When that happens, enter `app_state` and `path` to the prompt to print the content and path of the app manifest that is causing the error. Then copy paste the output here; it should look something like this:

```
python -m pdb -c continue -m protontricks.cli -v --gui
protontricks (INFO): Found Steam directory at /home/matoking/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/matoking/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 3 Steam library folders
Traceback (most recent call last):
  File "/usr/lib/python3.9/pdb.py", line 1703, in main
    pdb._runmodule(mainpyfile)
  File "/usr/lib/python3.9/pdb.py", line 1547, in _runmodule
    self.run(code)
  File "/usr/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 11, in <module>
    import argparse
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 180, in main
    steam_apps = get_steam_apps(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 860, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 190, in from_appmanifest
    name = app_state["name"]
KeyError: 'name'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python3.9/site-packages/protontricks/steam.py(190)from_appmanifest()
-> name = app_state["name"]
(Pdb) app_state
{'appid': '34900', 'universe': '1', 'nome': 'Bad Rats', 'stateflags': '4', 'installdir': 'Bad Rats', 'lastupdated': '1545430289', 'updateresult': '0', 'sizeondisk': '290674946', 'buildid': '540', 'lastowner': '76561197997662271', 'bytestodownload': '0', 'bytesdownloaded': '0', 'autoupdatebehavior': '0', 'allowotherdownloadswhilerunning': '0', 'scheduledautoupdate': '0', 'installeddepots': {'34903': {'manifest': '8382826086495783021', 'size': '0'}}, 'userconfig': {'language': 'english', 'platform_override_dest': 'linux', 'platform_override_source': 'windows'}}
(Pdb) path
PosixPath('/home/matoking/.steam/steam/steamapps/appmanifest_34900.acf')
```

**Comment by JPLeBreton** [comment] 2021-05-29 16:16
Ah, great idea. Here's the output:
```
protontricks (INFO): Found Steam directory at /home/jpl/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/jpl/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Multiple compatdata directories found for app 275850
Traceback (most recent call last):
  File "/usr/lib/python3.9/pdb.py", line 1703, in main
    pdb._runmodule(mainpyfile)
  File "/usr/lib/python3.9/pdb.py", line 1547, in _runmodule
    self.run(code)
  File "/usr/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 11, in <module>
    import argparse
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 180, in main
    steam_apps = get_steam_apps(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 860, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 190, in from_appmanifest
    name = app_state["name"]
KeyError: 'name'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python3.9/site-packages/protontricks/steam.py(190)from_appmanifest()
-> name = app_state["name"]
(Pdb) app_state
{'appid': '70', 'universe': '1', 'stateflags': '4', 'installdir': 'Half-Life', 'lastupdated': '1364877571', 'updateresult': '0', 'sizeondisk': '640481329', 'buildid': '55928', 'bytestodownload': '0', 'bytesdownloaded': '0', 'userconfig': {'name': 'Half-Life', 'GameID': '70', 'Installed': '1', 'appinstalldir': '/mnt/hausu/jpl/game/SteamLibrary/SteamApps/common/Half-Life', 'Language': 'english', 'betakey': 'public'}, 'mounteddepots': {'1': '5973466021040299584', '3': '3857850344229267146', '71': '2606120061184705776', '96': '8007990985538868417', '8': '814722121013004807'}}
(Pdb) path
PosixPath('/mnt/hausu/jpl/game/SteamLibrary/steamapps/appmanifest_70.acf')
```

**Comment by JPLeBreton** [comment] 2021-05-29 18:04
I did some quick Python REPL exploration of all the acf files in both my steam game directories, and Half-Life is the only one whose VDF data doesn't have a "name" key. That one app's name is instead stored inside a "UserConfig" block. I'm not sure how common this is; it might be limited to just Half-Life, which of course has other steam app ids (Blue Shift, Team Fortress Classic, etc) that use its InstallDir. Regardless, it's a widely owned game so handling that case seems like the fix.

**Comment by Matoking** [comment] 2021-05-30 12:59
This seems to be a case where the game was first installed years ago using an older version of Steam which used the `userconfig/name` field instead of just `name` to store the application name; the timestamp in your app manifest dates back to 2013 and some googling suggests that's what used to be the case. I wasn't able to reproduce the issue by installing Half-Life.

I've pushed a fix to the `userconfig_name_fix` branch, which you can install using pipx:

```
$ sudo pacman -S python-pipx
$ pipx install --force git+https://github.com/Matoking/protontricks.git@userconfig_name_fix
```

You may need to reopen the terminal before the installation is detected. Also, `/usr/bin/protontricks` might override the pipx installed version of Protontricks, so you may need to uninstall the AUR version before you can test the fix, or run `~/.local/bin/protontricks` instead.

Can you check whether that bug fix takes care of the problem, or if there are still other lingering issues?

**Comment by JPLeBreton** [comment] 2021-05-30 16:38
Yep, just confirmed that your bugfix allows me to run the two commands at the top of this report, with no other issues I can detect. Thanks much! This install of Steam is rather old, so it makes sense that that was behind the issue.

**Comment by Matoking** [comment] 2021-05-31 16:06
Great, thanks for the help!

**Closed** 2021-05-31 16:07 UTC
